name: Terraform Provider Checks

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/terraform_provider.yml
      - twilio/**
      - go.sum
      - makefile
      - main.go

jobs:
  pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      
      - name: Install tools
        run: make tools

      - name: Download Dependencies
        run: make download

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Refresh Go Report Card
        if: github.ref == 'refs/heads/main'
        continue-on-error: true
        timeout-minutes: 2
        run: make goreportcard-refresh
